### ISSUE TITLE
Readme file

### ISSUE THREAD

**Issue by zaha0077** [zaha0077/csci3010_pe6#5]
Just so you know, Person 3, the current Readme.md appears to be empty. Did you perhaps forget to save your changes to it?

**Comment by ghost** [comment]
So I need our repos url on Travis Ci to get it to work. Do either of you
have that?

**Comment by zaha0077** [comment]
I left it in my review for the cow. Reposting for convenience.

https://travis-ci.com/zaha0077/csci3010_pe6

Also speaking of that, you two should probably review each other's branches and merge before 9:30 AM.

I will hold off on submitting the github link to moodle until 1:00 AM. There's nothing saying you can't finish your parts after the submission, so don't worry if you can't get to your last steps until morning.

**Comment by ghost** [comment]
I merged mine and did the readme. My portion is done as my cow branched has
been merged in after I fixed the merge conflict on mine.

**Comment by zaha0077** [comment]
I noticed that our names weren't on the readme. I added in spaces for them.

**Comment by sesh4314** [comment]
Yeah I just got home, sorry. I finished resolving my conflicts and will add whatever is necessary in the readme.
